---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-pod-autoscaler
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "sample.javaoperatorsdk"
    resources:
      - leaderelections
      - leaderelections/status
    verbs:
      - '*'
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - '*'
