---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-pod-autoscaler
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "com.brandwatch"
    resources:
      - kafkapodautoscalers
      - kafkapodautoscalers/status
    verbs:
      - '*'
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - '*'
  - apiGroups:
      - '*'
    resources:
      - deployments
      - statefulsets
      - cronjobs
      - daemonsets
    verbs:
      - '*'
  - apiGroups:
      - '*'
    resources:
      - deployments/scale
      - statefulsets/scale
      - cronjobs/scale
      - daemonsets/scale
    verbs:
      - '*'
