---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-pod-autoscaler
spec:
  selector:
    matchLabels:
      app: kafka-pod-autoscaler
  template:
    metadata:
      labels:
        app: kafka-pod-autoscaler
    spec:
      serviceAccountName: kafka-pod-autoscaler
      containers:
        - name: operator
          image: kafka-pod-autoscaler
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Dlog.level=DEBUG
            - name: JAVA_OPTS_DEBUG
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
