---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-pod-autoscaler
spec:
  selector:
    matchLabels:
      app: kafka-pod-autoscaler
  template:
    metadata:
      labels:
        app: kafka-pod-autoscaler
    spec:
      serviceAccountName: kafka-pod-autoscaler
      containers:
        - name: operator
          image: kafka-pod-autoscaler
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 100m
              memory: 512Mi
