---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/kafkapodautoscaler.brandwatch.com-v1alpha1.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml

images:
  - name: kafka-pod-autoscaler
    newName: kafka-pod-autoscaler
    newTag: latest
