# Custom Resource Definition that will be used to generate the Java classes in target/generated-sources/java
# See https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md
# The Java classes will then be used to recreate this CR in target/classes/
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkapodautoscalers.com.brandwatch
spec:
  group: com.brandwatch
  names:
    kind: KafkaPodAutoscaler
    singular: kafkapodautoscaler
    plural: kafkapodautoscalers
    shortNames:
    - kpa
    - kpas
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
              - scaleTargetRef
              - triggers
            properties:
              dryRun:
                type: boolean
                default: false
              scaleTargetRef:
                type: object
                required:
                  - name
                  - apiVersion
                  - kind
                properties:
                  name:
                    type: string
                  apiVersion:
                    type: string
                  kind:
                    type: string
                    default: Deployment
              bootstrapServers:
                type: string
              topicName:
                type: string
              triggers:
                type: array
                nullable: false
                default: []
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
                    status:
                      type: object
                      properties:
                        inputValue:
                          type: number
                          format: double
                        targetThreshold:
                          type: number
                          format: double
                        recommendedReplicas:
                          type: integer
                          format: int32
          status:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
                description: The date and time that this message was added
                example: "2021-01-30T08:30:00Z"
              message:
                type: string
              dryRunReplicas:
                type: integer
                format: int32
              partitionCount:
                type: integer
                format: int32
              currentReplicaCount:
                type: integer
                format: int32
              calculatedReplicaCount:
                type: integer
                format: int32
              finalReplicaCount:
                type: integer
                format: int32

    served: true
    storage: true
    subresources:
      status: {}
