# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven verify

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: maven-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Cache build output
      if: github.ref_name == 'main'
      id: cache-output
      uses: actions/cache@v3
      with:
        path: target
        key: build-output-${{ github.sha }}

    - name: Build with Maven
      run: mvn -B verify

    - name: Check for unstaged changes
      run: |-
        if [[ -z $(git status -s) ]]; then
          echo "No unstaged changes"
        else
          echo "There are unstaged changes after the Maven build.  Did you check in the updated CRD?"
          git status
          git diff
          exit 1
        fi

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      if: github.actor != 'dependabot[bot]'
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
